# CandyParty dataset generation (v0)

Generated for Hugging Face: https://huggingface.co/datasets/jmaasch/compositional_causal_reasoning/

Version 0.

Code by Jacqueline Maasch | April 2025

In [1]:
# General importations.
import pandas as pd
import numpy as np

from utils import Utils
from candy_party import CandyParty
from dataset_generator import DataSetGenerator

In [2]:
u = Utils()
dg = DataSetGenerator()

In [3]:
import os
path = "static_datasets/candy_party_v0/"
os.makedirs(path, exist_ok=True)

## Step 1: Get raw dataset.

In [4]:
# x levels of graphical complexity (captured by BCC size).
# y tasks per graphical complexity level.
# z samples per task.
# w replicates per sample.
# = x*y*z*w subtasks.
graph_sizes = [[6,4,6],[7,5,7],[8,6,8]]
n_tasks_per_size = 1
n_samples_per_task = 2000
reps_per_sample = 5
bcc_type = "wheel"
causal_functions = "random"

df = dg.get_dataset(task_generator = CandyParty,
                    graph_sizes = graph_sizes,
                    n_tasks_per_size = n_tasks_per_size,
                    n_samples_per_task = n_samples_per_task, 
                    reps_per_sample = reps_per_sample, 
                    causal_functions = causal_functions, 
                    bcc_type = bcc_type)

print(df.info())
display(df.head(5))
display(df.tail(5))

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 30000 entries, 0 to 29999
Data columns (total 19 columns):
 #   Column                                  Non-Null Count  Dtype
---  ------                                  --------------  -----
 0   Task ID                                 30000 non-null  object
 1   Context ID                              30000 non-null  object
 2   Sample ID                               30000 non-null  object
 3   Nodes per BCC                           30000 non-null  object
 4   Replicate ID                            30000 non-null  int64
 5   DAG adjacency matrix                    30000 non-null  object
 6   DAG nodes                               30000 non-null  object
 7   CCT adjacency matrix                    30000 non-null  object
 8   CCT nodes                               30000 non-null  object
 9   Exogenous variables                     30000 non-null  object
 10  Bernoulli parameters                    30000 non-null  object
 11  Global quantity                         30000 non-null  object
 12  Local quantities                        30000 non-null  object
 13  Compositions                            30000 non-null  object
 14  Causal context                          30000 non-null  object
 15  Sample context                          30000 non-null  object
 16  Factual queries                         30000 non-null  object
 17  Interventional queries (cause = True)   30000 non-null  object
 18  Interventional queries (cause = False)  30000 non-null  object
dtypes: int64(1), object(18)
memory usage: 4.3+ MB
None

,Task ID,Context ID,Sample ID,Nodes per BCC,Replicate ID,DAG adjacency matrix,DAG nodes,CCT adjacency matrix,CCT nodes,Exogenous variables,Bernoulli parameters,Global quantity,Local quantities,Compositions,Causal context,Sample context,Factual queries,Interventional queries (cause = True),Interventional queries (cause = False)
0,0.0.0,0,0,"[6, 4, 6]",0,"[[0, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0], [...","[Luda, Delcie, Raelyn, Clair, Hailie, Reece, M...","[[0, 1, 1, 1], [0, 0, 1, 1], [0, 0, 0, 1], [0,...","[Luda, Reece, Zadie, Mckinley]","[JXLW, 8MMT, 2Y09, 8UNJ, X659, 7M8K, DDUN, PH7...","[0.4, 0.7, 0.4, 0.7, 0.8, 0.8, 0.4, 0.7, 0.7, ...","(Luda, Mckinley)","[(Luda, Reece), (Luda, Zadie), (Reece, Zadie),...","[[(Luda, Reece), (Reece, Zadie), (Zadie, Mckin...",A group of friends is going to a party where c...,"After distributing the candies, Luda gets 6 c...",{'Mckinley': {'Prompt': 'Is Mckinley happy? Be...,"{('Luda', 'Mckinley'): {'Prompt': 'Now, suppos...","{('Luda', 'Mckinley'): {'Prompt': 'Now, suppos..."
1,0.0.1,0,0,"[6, 4, 6]",1,"[[0, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0], [...","[Luda, Delcie, Raelyn, Clair, Hailie, Reece, M...","[[0, 1, 1, 1], [0, 0, 1, 1], [0, 0, 0, 1], [0,...","[Luda, Reece, Zadie, Mckinley]","[JXLW, 8MMT, 2Y09, 8UNJ, X659, 7M8K, DDUN, PH7...","[0.4, 0.7, 0.4, 0.7, 0.8, 0.8, 0.4, 0.7, 0.7, ...","(Luda, Mckinley)","[(Luda, Reece), (Luda, Zadie), (Reece, Zadie),...","[[(Luda, Reece), (Reece, Zadie), (Zadie, Mckin...",A group of friends is going to a party where c...,"After distributing the candies, Luda gets 6 c...",{'Mckinley': {'Prompt': 'Is Mckinley happy? Be...,"{('Luda', 'Mckinley'): {'Prompt': 'Now, suppos...","{('Luda', 'Mckinley'): {'Prompt': 'Now, suppos..."
2,0.0.2,0,0,"[6, 4, 6]",2,"[[0, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0], [...","[Luda, Delcie, Raelyn, Clair, Hailie, Reece, M...","[[0, 1, 1, 1], [0, 0, 1, 1], [0, 0, 0, 1], [0,...","[Luda, Reece, Zadie, Mckinley]","[JXLW, 8MMT, 2Y09, 8UNJ, X659, 7M8K, DDUN, PH7...","[0.4, 0.7, 0.4, 0.7, 0.8, 0.8, 0.4, 0.7, 0.7, ...","(Luda, Mckinley)","[(Luda, Reece), (Luda, Zadie), (Reece, Zadie),...","[[(Luda, Reece), (Reece, Zadie), (Zadie, Mckin...",A group of friends is going to a party where c...,"After distributing the candies, Luda gets 6 c...",{'Mckinley': {'Prompt': 'Is Mckinley happy? Be...,"{('Luda', 'Mckinley'): {'Prompt': 'Now, suppos...","{('Luda', 'Mckinley'): {'Prompt': 'Now, suppos..."
3,0.0.3,0,0,"[6, 4, 6]",3,"[[0, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0], [...","[Luda, Delcie, Raelyn, Clair, Hailie, Reece, M...","[[0, 1, 1, 1], [0, 0, 1, 1], [0, 0, 0, 1], [0,...","[Luda, Reece, Zadie, Mckinley]","[JXLW, 8MMT, 2Y09, 8UNJ, X659, 7M8K, DDUN, PH7...","[0.4, 0.7, 0.4, 0.7, 0.8, 0.8, 0.4, 0.7, 0.7, ...","(Luda, Mckinley)","[(Luda, Reece), (Luda, Zadie), (Reece, Zadie),...","[[(Luda, Reece), (Reece, Zadie), (Zadie, Mckin...",A group of friends is going to a party where c...,"After distributing the candies, Luda gets 6 c...",{'Mckinley': {'Prompt': 'Is Mckinley happy? Be...,"{('Luda', 'Mckinley'): {'Prompt': 'Now, suppos...","{('Luda', 'Mckinley'): {'Prompt': 'Now, suppos..."
4,0.0.4,0,0,"[6, 4, 6]",4,"[[0, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0], [...","[Luda, Delcie, Raelyn, Clair, Hailie, Reece, M...","[[0, 1, 1, 1], [0, 0, 1, 1], [0, 0, 0, 1], [0,...","[Luda, Reece, Zadie, Mckinley]","[JXLW, 8MMT, 2Y09, 8UNJ, X659, 7M8K, DDUN, PH7...","[0.4, 0.7, 0.4, 0.7, 0.8, 0.8, 0.4, 0.7, 0.7, ...","(Luda, Mckinley)","[(Luda, Reece), (Luda, Zadie), (Reece, Zadie),...","[[(Luda, Reece), (Reece, Zadie), (Zadie, Mckin...",A group of friends is going to a party where c...,"After distributing the candies, Luda gets 6 c...",{'Mckinley': {'Prompt': 'Is Mckinley happy? Be...,"{('Luda', 'Mckinley'): {'Prompt': 'Now, suppos...","{('Luda', 'Mckinley'): {'Prompt': 'Now, suppos..."

,Task ID,Context ID,Sample ID,Nodes per BCC,Replicate ID,DAG adjacency matrix,DAG nodes,CCT adjacency matrix,CCT nodes,Exogenous variables,Bernoulli parameters,Global quantity,Local quantities,Compositions,Causal context,Sample context,Factual queries,Interventional queries (cause = True),Interventional queries (cause = False)
29995,2.1999.0,2,1999,"[8, 6, 8]",0,"[[0, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0,...","[Kathleen, Arta, Danyel, Betha, Ayanna, Leone,...","[[0, 1, 1, 1], [0, 0, 1, 1], [0, 0, 0, 1], [0,...","[Kathleen, Susanna, Marianna, Christin]","[52KW, A1V8, C9X7, UL1D, X8OU, ARWT, TQGL, VUF...","[0.6, 0.4, 0.4, 0.8, 0.5, 0.7, 0.6, 0.5, 0.5, ...","(Kathleen, Christin)","[(Kathleen, Susanna), (Kathleen, Marianna), (S...","[[(Kathleen, Susanna), (Susanna, Marianna), (M...",A group of friends is going to a party where c...,"After distributing the candies, Kathleen gets...",{'Christin': {'Prompt': 'Is Christin happy? Be...,"{('Kathleen', 'Christin'): {'Prompt': 'Now, su...","{('Kathleen', 'Christin'): {'Prompt': 'Now, su..."
29996,2.1999.1,2,1999,"[8, 6, 8]",1,"[[0, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0,...","[Kathleen, Arta, Danyel, Betha, Ayanna, Leone,...","[[0, 1, 1, 1], [0, 0, 1, 1], [0, 0, 0, 1], [0,...","[Kathleen, Susanna, Marianna, Christin]","[52KW, A1V8, C9X7, UL1D, X8OU, ARWT, TQGL, VUF...","[0.6, 0.4, 0.4, 0.8, 0.5, 0.7, 0.6, 0.5, 0.5, ...","(Kathleen, Christin)","[(Kathleen, Susanna), (Kathleen, Marianna), (S...","[[(Kathleen, Susanna), (Susanna, Marianna), (M...",A group of friends is going to a party where c...,"After distributing the candies, Kathleen gets...",{'Christin': {'Prompt': 'Is Christin happy? Be...,"{('Kathleen', 'Christin'): {'Prompt': 'Now, su...","{('Kathleen', 'Christin'): {'Prompt': 'Now, su..."
29997,2.1999.2,2,1999,"[8, 6, 8]",2,"[[0, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0,...","[Kathleen, Arta, Danyel, Betha, Ayanna, Leone,...","[[0, 1, 1, 1], [0, 0, 1, 1], [0, 0, 0, 1], [0,...","[Kathleen, Susanna, Marianna, Christin]","[52KW, A1V8, C9X7, UL1D, X8OU, ARWT, TQGL, VUF...","[0.6, 0.4, 0.4, 0.8, 0.5, 0.7, 0.6, 0.5, 0.5, ...","(Kathleen, Christin)","[(Kathleen, Susanna), (Kathleen, Marianna), (S...","[[(Kathleen, Susanna), (Susanna, Marianna), (M...",A group of friends is going to a party where c...,"After distributing the candies, Kathleen gets...",{'Christin': {'Prompt': 'Is Christin happy? Be...,"{('Kathleen', 'Christin'): {'Prompt': 'Now, su...","{('Kathleen', 'Christin'): {'Prompt': 'Now, su..."
29998,2.1999.3,2,1999,"[8, 6, 8]",3,"[[0, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0,...","[Kathleen, Arta, Danyel, Betha, Ayanna, Leone,...","[[0, 1, 1, 1], [0, 0, 1, 1], [0, 0, 0, 1], [0,...","[Kathleen, Susanna, Marianna, Christin]","[52KW, A1V8, C9X7, UL1D, X8OU, ARWT, TQGL, VUF...","[0.6, 0.4, 0.4, 0.8, 0.5, 0.7, 0.6, 0.5, 0.5, ...","(Kathleen, Christin)","[(Kathleen, Susanna), (Kathleen, Marianna), (S...","[[(Kathleen, Susanna), (Susanna, Marianna), (M...",A group of friends is going to a party where c...,"After distributing the candies, Kathleen gets...",{'Christin': {'Prompt': 'Is Christin happy? Be...,"{('Kathleen', 'Christin'): {'Prompt': 'Now, su...","{('Kathleen', 'Christin'): {'Prompt': 'Now, su..."
29999,2.1999.4,2,1999,"[8, 6, 8]",4,"[[0, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0,...","[Kathleen, Arta, Danyel, Betha, Ayanna, Leone,...","[[0, 1, 1, 1], [0, 0, 1, 1], [0, 0, 0, 1], [0,...","[Kathleen, Susanna, Marianna, Christin]","[52KW, A1V8, C9X7, UL1D, X8OU, ARWT, TQGL, VUF...","[0.6, 0.4, 0.4, 0.8, 0.5, 0.7, 0.6, 0.5, 0.5, ...","(Kathleen, Christin)","[(Kathleen, Susanna), (Kathleen, Marianna), (S...","[[(Kathleen, Susanna), (Susanna, Marianna), (M...",A group of friends is going to a party where c...,"After distributing the candies, Kathleen gets...",{'Christin': {'Prompt': 'Is Christin happy? Be...,"{('Kathleen', 'Christin'): {'Prompt': 'Now, su...","{('Kathleen', 'Christin'): {'Prompt': 'Now, su..."

In [5]:
df.to_csv(path+"candy_party_v0.csv", index = False)

## Step 2: Process factual and counterfactual prompts.

In [6]:
# Process prompts.
df_factual, df_cf = dg.process_prompts()

In [7]:
print(df_factual.info())
display(df_factual.head(5))

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 90000 entries, 0 to 89999
Data columns (total 9 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Task ID        90000 non-null  object
 1   Context ID     90000 non-null  int64
 2   Sample ID      90000 non-null  int64
 3   Replicate ID   90000 non-null  int64
 4   Nodes per BCC  90000 non-null  object
 5   Effect         90000 non-null  object
 6   Context        90000 non-null  object
 7   Question       90000 non-null  object
 8   True           90000 non-null  int64
dtypes: int64(4), object(5)
memory usage: 6.2+ MB
None

,Task ID,Context ID,Sample ID,Replicate ID,Nodes per BCC,Effect,Context,Question,True
0,0.0.0,0,0,0,"[6, 4, 6]",Mckinley,A group of friends is going to a party where c...,Is Mckinley happy? Begin your response with Ye...,1
1,0.0.0,0,0,0,"[6, 4, 6]",Reece,A group of friends is going to a party where c...,Is Reece happy? Begin your response with Yes o...,1
2,0.0.0,0,0,0,"[6, 4, 6]",Zadie,A group of friends is going to a party where c...,Is Zadie happy? Begin your response with Yes o...,1
3,0.0.1,0,0,1,"[6, 4, 6]",Mckinley,A group of friends is going to a party where c...,Is Mckinley happy? Begin your response with Ye...,1
4,0.0.1,0,0,1,"[6, 4, 6]",Reece,A group of friends is going to a party where c...,Is Reece happy? Begin your response with Yes o...,1

In [8]:
print(df_cf.info())
display(df_cf.head(5))

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 180000 entries, 0 to 179999
Data columns (total 13 columns):
 #   Column                    Non-Null Count   Dtype
---  ------                    --------------   -----
 0   Task ID                   180000 non-null  object
 1   Context ID                180000 non-null  int64
 2   Sample ID                 180000 non-null  int64
 3   Replicate ID              180000 non-null  int64
 4   Nodes per BCC             180000 non-null  object
 5   Cause-effect pair         180000 non-null  object
 6   Cause                     180000 non-null  object
 7   Effect                    180000 non-null  object
 8   Context                   180000 non-null  object
 9   Question (cause = True)   180000 non-null  object
 10  True (cause = True)       180000 non-null  int64
 11  Question (cause = False)  180000 non-null  object
 12  True (cause = False)      180000 non-null  int64
dtypes: int64(5), object(8)
memory usage: 17.9+ MB
None

,Task ID,Context ID,Sample ID,Replicate ID,Nodes per BCC,Cause-effect pair,Cause,Effect,Context,Question (cause = True),True (cause = True),Question (cause = False),True (cause = False)
0,0.0.0,0,0,0,"[6, 4, 6]","(Luda, Mckinley)",Luda,Mckinley,A group of friends is going to a party where c...,"Now, suppose that Luda is happy regardless of ...",1,"Now, suppose that Luda is not happy regardless...",1
1,0.0.0,0,0,0,"[6, 4, 6]","(Luda, Reece)",Luda,Reece,A group of friends is going to a party where c...,"Now, suppose that Luda is happy regardless of ...",1,"Now, suppose that Luda is not happy regardless...",0
2,0.0.0,0,0,0,"[6, 4, 6]","(Luda, Zadie)",Luda,Zadie,A group of friends is going to a party where c...,"Now, suppose that Luda is happy regardless of ...",1,"Now, suppose that Luda is not happy regardless...",1
3,0.0.0,0,0,0,"[6, 4, 6]","(Reece, Zadie)",Reece,Zadie,A group of friends is going to a party where c...,"Now, suppose that Reece is happy regardless of...",1,"Now, suppose that Reece is not happy regardles...",1
4,0.0.0,0,0,0,"[6, 4, 6]","(Reece, Mckinley)",Reece,Mckinley,A group of friends is going to a party where c...,"Now, suppose that Reece is happy regardless of...",1,"Now, suppose that Reece is not happy regardles...",1

In [9]:
df_cf.head(30)

,Task ID,Context ID,Sample ID,Replicate ID,Nodes per BCC,Cause-effect pair,Cause,Effect,Context,Question (cause = True),True (cause = True),Question (cause = False),True (cause = False)
0,0.0.0,0,0,0,"[6, 4, 6]","(Luda, Mckinley)",Luda,Mckinley,A group of friends is going to a party where c...,"Now, suppose that Luda is happy regardless of ...",1,"Now, suppose that Luda is not happy regardless...",1
1,0.0.0,0,0,0,"[6, 4, 6]","(Luda, Reece)",Luda,Reece,A group of friends is going to a party where c...,"Now, suppose that Luda is happy regardless of ...",1,"Now, suppose that Luda is not happy regardless...",0
2,0.0.0,0,0,0,"[6, 4, 6]","(Luda, Zadie)",Luda,Zadie,A group of friends is going to a party where c...,"Now, suppose that Luda is happy regardless of ...",1,"Now, suppose that Luda is not happy regardless...",1
3,0.0.0,0,0,0,"[6, 4, 6]","(Reece, Zadie)",Reece,Zadie,A group of friends is going to a party where c...,"Now, suppose that Reece is happy regardless of...",1,"Now, suppose that Reece is not happy regardles...",1
4,0.0.0,0,0,0,"[6, 4, 6]","(Reece, Mckinley)",Reece,Mckinley,A group of friends is going to a party where c...,"Now, suppose that Reece is happy regardless of...",1,"Now, suppose that Reece is not happy regardles...",1
5,0.0.0,0,0,0,"[6, 4, 6]","(Zadie, Mckinley)",Zadie,Mckinley,A group of friends is going to a party where c...,"Now, suppose that Zadie is happy regardless of...",1,"Now, suppose that Zadie is not happy regardles...",1
6,0.0.1,0,0,1,"[6, 4, 6]","(Luda, Mckinley)",Luda,Mckinley,A group of friends is going to a party where c...,"Now, suppose that Luda is happy regardless of ...",1,"Now, suppose that Luda is not happy regardless...",1
7,0.0.1,0,0,1,"[6, 4, 6]","(Luda, Reece)",Luda,Reece,A group of friends is going to a party where c...,"Now, suppose that Luda is happy regardless of ...",1,"Now, suppose that Luda is not happy regardless...",0
8,0.0.1,0,0,1,"[6, 4, 6]","(Luda, Zadie)",Luda,Zadie,A group of friends is going to a party where c...,"Now, suppose that Luda is happy regardless of ...",1,"Now, suppose that Luda is not happy regardless...",1
9,0.0.1,0,0,1,"[6, 4, 6]","(Reece, Zadie)",Reece,Zadie,A group of friends is going to a party where c...,"Now, suppose that Reece is happy regardless of...",1,"Now, suppose that Reece is not happy regardles...",1
10,0.0.1,0,0,1,"[6, 4, 6]","(Reece, Mckinley)",Reece,Mckinley,A group of friends is going to a party where c...,"Now, suppose that Reece is happy regardless of...",1,"Now, suppose that Reece is not happy regardles...",1
11,0.0.1,0,0,1,"[6, 4, 6]","(Zadie, Mckinley)",Zadie,Mckinley,A group of friends is going to a party where c...,"Now, suppose that Zadie is happy regardless of...",1,"Now, suppose that Zadie is not happy regardles...",1
12,0.0.2,0,0,2,"[6, 4, 6]","(Luda, Mckinley)",Luda,Mckinley,A group of friends is going to a party where c...,"Now, suppose that Luda is happy regardless of ...",1,"Now, suppose that Luda is not happy regardless...",1
13,0.0.2,0,0,2,"[6, 4, 6]","(Luda, Reece)",Luda,Reece,A group of friends is going to a party where c...,"Now, suppose that Luda is happy regardless of ...",1,"Now, suppose that Luda is not happy regardless...",0
14,0.0.2,0,0,2,"[6, 4, 6]","(Luda, Zadie)",Luda,Zadie,A group of friends is going to a party where c...,"Now, suppose that Luda is happy regardless of ...",1,"Now, suppose that Luda is not happy regardless...",1
15,0.0.2,0,0,2,"[6, 4, 6]","(Reece, Zadie)",Reece,Zadie,A group of friends is going to a party where c...,"Now, suppose that Reece is happy regardless of...",1,"Now, suppose that Reece is not happy regardles...",1
16,0.0.2,0,0,2,"[6, 4, 6]","(Reece, Mckinley)",Reece,Mckinley,A group of friends is going to a party where c...,"Now, suppose that Reece is happy regardless of...",1,"Now, suppose that Reece is not happy regardles...",1
17,0.0.2,0,0,2,"[6, 4, 6]","(Zadie, Mckinley)",Zadie,Mckinley,A group of friends is going to a party where c...,"Now, suppose that Zadie is happy regardless of...",1,"Now, suppose that Zadie is not happy regardles...",1
18,0.0.3,0,0,3,"[6, 4, 6]","(Luda, Mckinley)",Luda,Mckinley,A group of friends is going to a party where c...,"Now, suppose that Luda is happy regardless of ...",1,"Now, suppose that Luda is not happy regardless...",1
19,0.0.3,0,0,3,"[6, 4, 6]","(Luda, Reece)",Luda,Reece,A group of friends is going to a party where c...,"Now, suppose that Luda is happy regardless of ...",1,"Now, suppose that Luda is not happy regardless...",0
20,0.0.3,0,0,3,"[6, 4, 6]","(Luda, Zadie)",Luda,Zadie,A group of friends is going to a party where c...,"Now, suppose that Luda is happy regardless of ...",1,"Now, suppose that Luda is not happy regardless...",1
21,0.0.3,0,0,3,"[6, 4, 6]","(Reece, Zadie)",Reece,Zadie,A group of friends is going to a party where c...,"Now, suppose that Reece is happy regardless of...",1,"Now, suppose that Reece is not happy regardles...",1
22,0.0.3,0,0,3,"[6, 4, 6]","(Reece, Mckinley)",Reece,Mckinley,A group of friends is going to a party where c...,"Now, suppose that Reece is happy regardless of...",1,"Now, suppose that Reece is not happy regardles...",1
23,0.0.3,0,0,3,"[6, 4, 6]","(Zadie, Mckinley)",Zadie,Mckinley,A group of friends is going to a party where c...,"Now, suppose that Zadie is happy regardless of...",1,"Now, suppose that Zadie is not happy regardles...",1
24,0.0.4,0,0,4,"[6, 4, 6]","(Luda, Mckinley)",Luda,Mckinley,A group of friends is going to a party where c...,"Now, suppose that Luda is happy regardless of ...",1,"Now, suppose that Luda is not happy regardless...",1
25,0.0.4,0,0,4,"[6, 4, 6]","(Luda, Reece)",Luda,Reece,A group of friends is going to a party where c...,"Now, suppose that Luda is happy regardless of ...",1,"Now, suppose that Luda is not happy regardless...",0
26,0.0.4,0,0,4,"[6, 4, 6]","(Luda, Zadie)",Luda,Zadie,A group of friends is going to a party where c...,"Now, suppose that Luda is happy regardless of ...",1,"Now, suppose that Luda is not happy regardless...",1
27,0.0.4,0,0,4,"[6, 4, 6]","(Reece, Zadie)",Reece,Zadie,A group of friends is going to a party where c...,"Now, suppose that Reece is happy regardless of...",1,"Now, suppose that Reece is not happy regardles...",1
28,0.0.4,0,0,4,"[6, 4, 6]","(Reece, Mckinley)",Reece,Mckinley,A group of friends is going to a party where c...,"Now, suppose that Reece is happy regardless of...",1,"Now, suppose that Reece is not happy regardles...",1
29,0.0.4,0,0,4,"[6, 4, 6]","(Zadie, Mckinley)",Zadie,Mckinley,A group of friends is going to a party where c...,"Now, suppose that Zadie is happy regardless of...",1,"Now, suppose that Zadie is not happy regardles...",1

In [10]:
df_factual.to_csv(path+"candy_party_factual_v0.csv", index = False)

In [11]:
df_cf.to_csv(path+"candy_party_counterfactual_v0.csv", index = False)

In [12]:
# Dynamic check using actual effect from the dataset.
sample_effect = df_factual["Effect"].iloc[0]
l = len(df_factual[(df_factual["Context ID"] == 0) & (df_factual["Effect"] == sample_effect)])
print(f"\nTotal factual q's per quantity per task for '{sample_effect}':", l)

Total factual q's per quantity per task for 'Mckinley': 10000

In [13]:
# Dynamic check using actual cause-effect pair from the dataset.
sample_pair = df_cf["Cause-effect pair"].iloc[0]
l = len(df_cf[(df_cf["Context ID"] == 0) & (df_cf["Cause-effect pair"] == sample_pair)])
print(f"\nTotal counterfactual q's per quantity per task for {sample_pair}:", l)

Total counterfactual q's per quantity per task for ('Luda', 'Mckinley'): 10000

## Step 3: Get ground truth PNS values.

Get dictionary mapping cause-effect pairs to their PNS value.

Keys are the Context ID. Values are dictionaries whose keys are the cause-effect pair and whose values are the finite sample PNS computed using ground truth response vectors.

In [14]:
pns_dict = dg.get_pns_dict(verbose = False)
display(pns_dict)

{np.int64(0): {"('Luda', 'Mckinley')": np.float64(0.023),
  "('Luda', 'Reece')": np.float64(0.812),
  "('Luda', 'Zadie')": np.float64(0.0675),
  "('Reece', 'Zadie')": np.float64(0.084),
  "('Reece', 'Mckinley')": np.float64(0.0275),
  "('Zadie', 'Mckinley')": np.float64(0.3075),
  "[('Luda', 'Reece'), ('Reece', 'Zadie'), ('Zadie', 'Mckinley')]": np.float64(0.02097396),
  "[('Luda', 'Reece'), ('Reece', 'Mckinley')]": np.float64(0.022330000000000003),
  "[('Luda', 'Zadie'), ('Zadie', 'Mckinley')]": np.float64(0.02075625)},
 np.int64(1): {"('Annice', 'Bebe')": np.float64(0.0275),
  "('Annice', 'Venita')": np.float64(0.2395),
  "('Annice', 'Mckenzie')": np.float64(0.12),
  "('Venita', 'Mckenzie')": np.float64(0.5055),
  "('Venita', 'Bebe')": np.float64(0.128),
  "('Mckenzie', 'Bebe')": np.float64(0.2485),
  "[('Annice', 'Venita'), ('Venita', 'Mckenzie'), ('Mckenzie', 'Bebe')]": np.float64(0.030085211624999997),
  "[('Annice', 'Venita'), ('Venita', 'Bebe')]": np.float64(0.030656),
  "[('Annice', 'Mckenzie'), ('Mckenzie', 'Bebe')]": np.float64(0.02982)},
 np.int64(2): {"('Kathleen', 'Christin')": np.float64(0.0045),
  "('Kathleen', 'Susanna')": np.float64(0.124),
  "('Kathleen', 'Marianna')": np.float64(0.0095),
  "('Susanna', 'Marianna')": np.float64(0.083),
  "('Susanna', 'Christin')": np.float64(0.049),
  "('Marianna', 'Christin')": np.float64(0.5275),
  "[('Kathleen', 'Susanna'), ('Susanna', 'Marianna'), ('Marianna', 'Christin')]": np.float64(0.0054290300000000005),
  "[('Kathleen', 'Susanna'), ('Susanna', 'Christin')]": np.float64(0.006076),
  "[('Kathleen', 'Marianna'), ('Marianna', 'Christin')]": np.float64(0.005011249999999999)}}

In [15]:
# Save with numpy.
np.save(path+"candy_party_pns_dict_v0.npy", pns_dict) 

# Test loading.
#pns_dict_loaded = np.load("candy_party_pns_dict.npy",
#                          allow_pickle = "TRUE").item()
#display(pns_dict_loaded)

## Step 4: Compute internal consistency thresholds.

Return a dictionary that maps compositions to their correctness threshold
for internal compositional consistency evaluation. Thresholds are the RAE
for each composition relative to the global quantity of interest, times a
multiplier of the user's choice. 

* RAE = (abs(global PNS - composition PNS) / global PNS)
* Threshold = RAE*multiplier
        
This method of obtaining the threshold accounts for the innate error owed
to PNS estimation on finite samples, while the multiplier represents the
user's tolerance level for errors larger than the finite sample error.

Keys are the Context ID. Values are dictionaries whose keys are the causal composition (denoted by a list of cause-effect pairs whose PNS values are multiplied) and whose values are the internal consistency threshold.

For public use, we export thresholds with multiplier 1.0 so that the end user can select 
their own multiplier downstream.

In [16]:
# Not for export.
threshold_dict = dg.get_internal_consistency_thresholds(multiplier = 1.25)
display(threshold_dict)

{0: {"[('Luda', 'Reece'), ('Reece', 'Zadie'), ('Zadie', 'Mckinley')]": np.float64(0.11011086956521739),
  "[('Luda', 'Reece'), ('Reece', 'Mckinley')]": np.float64(0.03641304347826071),
  "[('Luda', 'Zadie'), ('Zadie', 'Mckinley')]": np.float64(0.12194293478260865)},
 1: {"[('Annice', 'Venita'), ('Venita', 'Mckenzie'), ('Mckenzie', 'Bebe')]": np.float64(0.11750961931818167),
  "[('Annice', 'Venita'), ('Venita', 'Bebe')]": np.float64(0.14345454545454542),
  "[('Annice', 'Mckenzie'), ('Mckenzie', 'Bebe')]": np.float64(0.10545454545454541)},
 2: {"[('Kathleen', 'Susanna'), ('Susanna', 'Marianna'), ('Marianna', 'Christin')]": np.float64(0.25806388888888915),
  "[('Kathleen', 'Susanna'), ('Susanna', 'Christin')]": np.float64(0.4377777777777778),
  "[('Kathleen', 'Marianna'), ('Marianna', 'Christin')]": np.float64(0.14201388888888877)}}

In [17]:
# For export.
threshold_dict = dg.get_internal_consistency_thresholds(multiplier = 1.0)
display(threshold_dict)

{0: {"[('Luda', 'Reece'), ('Reece', 'Zadie'), ('Zadie', 'Mckinley')]": np.float64(0.0880886956521739),
  "[('Luda', 'Reece'), ('Reece', 'Mckinley')]": np.float64(0.029130434782608565),
  "[('Luda', 'Zadie'), ('Zadie', 'Mckinley')]": np.float64(0.09755434782608692)},
 1: {"[('Annice', 'Venita'), ('Venita', 'Mckenzie'), ('Mckenzie', 'Bebe')]": np.float64(0.09400769545454533),
  "[('Annice', 'Venita'), ('Venita', 'Bebe')]": np.float64(0.11476363636363633),
  "[('Annice', 'Mckenzie'), ('Mckenzie', 'Bebe')]": np.float64(0.08436363636363634)},
 2: {"[('Kathleen', 'Susanna'), ('Susanna', 'Marianna'), ('Marianna', 'Christin')]": np.float64(0.2064511111111113),
  "[('Kathleen', 'Susanna'), ('Susanna', 'Christin')]": np.float64(0.35022222222222227),
  "[('Kathleen', 'Marianna'), ('Marianna', 'Christin')]": np.float64(0.11361111111111102)}}

In [18]:
# Save with numpy.
np.save(path+"candy_party_threshold_dict_v0.npy", threshold_dict) 

# Test loading.
#threshold_dict_loaded = np.load("candy_party_threshold_dict.npy",
#                                allow_pickle = "TRUE").item()
#display(threshold_dict_loaded)